version: "3.3"
services:
  nextjs:
    build: ./
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    network_mode: "host"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs
#    ports:
#      - "8081:80"
